### PR TITLE
Hack lang property typehint support & PHP7 getter typehint support

### PR DESCRIPTION
**Pull request by mihai-stancu**
- Fixing SensioInsights and Symfony2 code standards
- Moving tests to PSR-4 namespace and moving phpunit.xml to phpunit.xml.dist
- Removing PHPSpec

### CODE REVIEW

**Comment by dunglas** [comment]
Run PHP CS Fixer and Travis will be happy.

**Comment by soullivaneuh** [comment]
> Run PHP CS Fixer and Travis will be happy.

Nope, already done on #4 for most of the code.

PR is not up to date. @mihai-stancu, can you please rebase it from master?

**Comment by mihai-stancu** [comment]
It was a fresh branch from master (with the same name). The CS is not happy because I accidentally included a `phpunit.bootrap.php` file which is no longer necessary.

**Comment by mihai-stancu** [comment]
There's also the problem of the Php7 example data file which is considered to be "invalid syntax". I'd name it as `*.php7` but i don't know if the autoloader will work and I'd have to manually require it.

**Comment by dunglas** [comment]
Invalid syntax by PHP CS fixer? In that case exclude this file in .php_cs

**Comment by mihai-stancu** [comment]
Done.

**Comment by dunglas** [comment]
Thank you @mihai-stancu

**Pull request merged**
