### PR TITLE
Major refactoring to prepare the Symfony merge

### PR DESCRIPTION
**Pull request by dunglas**
This component will be integrated in Symfony 2.8/3.0. This PR prepares the merge and fix some design issues.
- [x] Support for PHP 5.3 (required by Symfony)
- [x] Support for "virtual" properties. Ex: no property but accessor methods (allow to fix some API Platform limitations). **BC break**.
- [x] Support for accessor methods in the `PhpDocExtractor`
- [x] Simplified test infrastructure
- [x] Refactored PHP7 ~~and Hack~~ support.
- [x] Property readability and writability detection

### CODE REVIEW

**Comment by mihai-stancu** [comment]
@dunglas I'm currently porting the Hack logic to this branch.

I have a few questions:

0. The new approach for reading data from properties, accessors and mutators only includes Hack-related logic for properties -- is this an intended change? -- Hack could very well read accessor return types and  mutator parameter types as well and parse TypeText from them.

0. Should the `TypeTextParser` class be `Hack`-only? I would assume `PhpDoc`s could be using `array<string, stdClass>` style annotations which would be parsable too.

**Comment by mihai-stancu** [comment]
@dunglas I see you've removed `property type` and `hack` support. Please let me know how you want to integrate #9 into the the new workflow.

**Comment by dunglas** [comment]
Hi Mihai,

Yes I still want to integrate it but as creating a test infrastructure for Hack in Symfony before 2.8/3.0 the feature freeze we'll delay the integration of Hack support in 3.1.
I'll open the PR in Symfony soon (I hope today) and we will be able to work on Hack support when it get merged.

**Comment by mihai-stancu** [comment]
OK then, we'll wait for 3.1.

**Comment by dunglas** [comment]
PR on Symfony: symfony/symfony#15858

**Pull request merged**
