### PR TITLE
Configure and apply cs-fixer

### PR DESCRIPTION
**Pull request by soullivaneuh**
- Cs-fixer job for Travis (check if CS passes)
- php-cs-fixer config:
  - Symfony level
  - Header Comment
  - Additionnal rules (see `.php_cs` file)

Feel free to comment the diff for remove or add some rules as you want to do.

Regards.

### CODE REVIEW

**Comment by dunglas** [comment]
Can you setup PHP CS Fixer 2.0? It will allow to use its cache in Travis: https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/master#using-php-cs-fixer-on-travis

**Comment by soullivaneuh** [comment]
Are you sure about it? 2.0 is not a stable version and people who want to correct CS issue on this project PRs will not use this version and the related fixer. Am I right?

I would prefer waiting for 2.0 stable. BTW, you don't have lot of file to scan on this project.

I let you decide. :+1:

**Comment by dunglas** [comment]
I agree we can wait for the stable release as we don't have so many files. Can you resolve conflicts?

**Comment by soullivaneuh** [comment]
Done.

**Comment by dunglas** [comment]
Thank you @Soullivaneuh

**Pull request merged**
